/*
 * THIS FILE IS AUTOGENERATED
 * MODIFY setup.py INSTEAD
*/
#include "vge.h"
void list_init();
void list_addremove();
void rbtree_init();
void rbtree_insert();
void rbtree_delete();

void expect(int result, char *errormsg)
{
	if(!result) {
		printf("%s\n", errormsg);
	}
}
void run_tests()
{
	struct vge_stopwatch sw;
	float time_elapsed;
	vge_stopwatch_reset(&sw);
	list_init();
	list_addremove();
	rbtree_init();
	rbtree_insert();
	rbtree_delete();
	time_elapsed = vge_stopwatch_elapsed(&sw);
	printf("Ran 5 tests in %2.3f\n", time_elapsed);
}
int main(int argc, char **argv)
{
	if(argc>1 && strcmp(argv[1], "test")==0) {
		run_tests();
	} else {
		printf("Running game_main()...\n");
		game_main(argc, argv);
	}
	return 0;
}
